inherit_from:
  # - ../.rubocop.

require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "config/environments/*"
    - "node_modules/**/*"

# Naming

Naming/MemoizedInstanceVariableName:
  Enabled: false

# Metrics Cops

Metrics/ClassLength:
  Description: "Avoid classes longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ModuleLength:
  Description: "Avoid modules longer than 100 lines of code."
  Max: 100
  Enabled: true

Metrics/ParameterLists:
  Description: "Pass no more than four parameters into a method."
  Max: 7
  Enabled: true

Metrics/MethodLength:
  Description: "Avoid methods longer than 5 lines of code."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#short-methods"
  Max: 15
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 5
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

# Style Cops

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false
  EnforcedStyle: nested

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    find: detect
    inject: reduce
    collect: map
    find_all: select

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
  Enabled: true
  EnforcedStyle: always

Style/IfUnlessModifier:
  Description: >-
    Favor modifier if/unless usage when you have a
    single-line body.
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#if-as-a-modifier"
  Enabled: false

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

Style/LineEndConcatenation:
  Description: >-
    Use \ instead of + or << to concatenate two string literals at
    line end.
  Enabled: true

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#consistent-string-literals"
  EnforcedStyle: single_quotes
  Enabled: true

# Layout Cops
Layout/FirstArrayElementIndentation:
  EnforcedStyle: special_inside_parentheses

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent_relative_to_receiver

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: same_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: same_line

Layout/LineLength:
  Description: "Limit lines to 120 characters."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#80-character-limits"
  Max: 120

Layout/MultilineOperationIndentation:
  Description: >-
    Checks indentation of binary operations that span more than
    one line.
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Description: >-
    Checks indentation of method calls with the dot operator
    that span more than one line.
  Enabled: true
  EnforcedStyle: indented

Layout/HashAlignment:
  EnforcedColonStyle: table


# Bundler Cops

Bundler/OrderedGems:
  Enabled: false

# RSpec
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/NestedGroups:
  Max: 5

RSpec/DescribeClass:
  Enabled: false